const types = {
  CHANGE_IS_SET: 'CHANGE_IS_SET',
  MEMBER: {
    SET_ORDER_QUERY_ONE_FORM_DATA: 'SET_ORDER_QUERY_ONE_FORM_DATA',
    NEW_ORDER_QUERY: 'NEW_ORDER_QUERY',
    END_NEW_ORDER_QUERY: 'END_NEW_ORDER_QUERY',
  }
}
export default types